name: 'Setup TFLint'
description: 'Sets up tflint CLI in your GitHub Actions workflow'
author: 'jgeurts'
inputs:
  tflint_version:
    description: TFLint version to install
    required: false
    default: latest
  github_token:
    description: GitHub token - used when getting the latest version of tflint
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'purple'
