name: 'Setup TFLint'
description: 'Sets up tflint CLI in your GitHub Actions workflow'
inputs:
  tflint_version:
    description: TFLint version to install
    required: false
    default: latest
  github_token:
    description: GitHub token - used when getting the latest version of tflint
    required: false
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  tflint_wrapper:
    description: Installs a wrapper script to wrap subsequent calls to `tflint` and expose `stdout`, `stderr`, and `exitcode` outputs
    default: 'false'
    required: false
  expected_sha256:
    description: The expected SHA256 hash of the downloaded TFLint binary. If provided, the action will verify the binary's integrity and only proceed if the hash matches.
    required: false
outputs:
  stdout:
    description: The output (stdout) produced by the tflint command. Only available if `tflint_wrapper` is set to `true`.
  stderr:
    description: The error output (stderr) produced by the tflint command. Only available if `tflint_wrapper` is set to `true`.
  exitcode:
    description: The exit code produced by the tflint command. Only available if `tflint_wrapper` is set to `true`.
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'purple'
